### ISSUE TITLE
Admin Console accessible only on bootstrap node

### ISSUE THREAD

**Issue by fgeorges** [marklogic/marklogic-docker#152]
> Hi.  I am not sure how to ask questions about this project.  Since there is a label `question` here, I guess this is OK here.

I have a 3-node cluster, all nodes on the same machine, based on `marklogic-cluster-centos.yml` (full code below.)

Each node has 20 ports mapped.  First ports `8000` through `8018`, then `7997` at the end:

- first node: `8300-8319` (last one is the health check)
- second node: `8320-8339` (last one is the health check)
- third node: `8340-8359` (last one is the health check)

So the Admin Console is accessible on resp. `8301`, `8321`, and `8341`.

After `sudo docker-compose up -d`, all seems fine (after a dozen of seconds, to complete the init phase.)  When I go to `http://localhost:8301/`, the Admin Console clearly shows that the cluster is comprised of 3 nodes, with the correct names.

But if I try to access the Admin Console on the 2 other nodes, using `http://localhost:8321/` or `http://localhost:8341/`, I never get a page back.  If I look in the access logs for `8001`, I can see the access for the first node (of course, this is the one responding,) but nothing for the 2 other nodes (besides the 5 Admin API calls performed during the init phase to join the cluster.)  If I look at network dev pane in the browser, I can see it sends the request but just keeps waiting for a response.

Any idea?  The complete `docker-compose.yml`:

```yaml
version: '3.8'

services:
   myproject-ape:
      container_name: myproject-ape
      hostname: myproject-ape
      image: marklogicdb/marklogic-db:10.0-9.4-centos-1.0.0-ea4
      environment:
         - MARKLOGIC_INIT=true
         - MARKLOGIC_ADMIN_USERNAME=admin
         - MARKLOGIC_ADMIN_PASSWORD=admin
         - TZ=Europe/Brussels
      ports:
         - 8319:7997
         - 8300-8318:8000-8018
      volumes:
         - myproject-ape-vol1:/var/opt/MarkLogic
      networks:
         - external_net

   myproject-bear:
      container_name: myproject-bear
      hostname: myproject-bear
      image: marklogicdb/marklogic-db:10.0-9.4-centos-1.0.0-ea4
      environment:
         - MARKLOGIC_INIT=true
         - MARKLOGIC_JOIN_CLUSTER=true
         - MARKLOGIC_BOOTSTRAP_HOST=myproject-ape
         - MARKLOGIC_ADMIN_USERNAME=admin
         - MARKLOGIC_ADMIN_PASSWORD=admin
         - TZ=Europe/Brussels
      ports:
         - 8339:7997
         - 8320-8338:8000-8018
      volumes:
         - myproject-bear-vol1:/var/opt/MarkLogic
      depends_on:
         - myproject-ape
      networks:
         - external_net

   myproject-cat:
      container_name: myproject-cat
      hostname: myproject-cat
      image: marklogicdb/marklogic-db:10.0-9.4-centos-1.0.0-ea4
      environment:
         - MARKLOGIC_INIT=true
         - MARKLOGIC_JOIN_CLUSTER=true
         - MARKLOGIC_BOOTSTRAP_HOST=myproject-ape
         - MARKLOGIC_ADMIN_USERNAME=admin
         - MARKLOGIC_ADMIN_PASSWORD=admin
         - TZ=Europe/Brussels
      ports:
         - 8359:7997
         - 8340-8358:8000-8018
      volumes:
         - myproject-cat-vol1:/var/opt/MarkLogic
      depends_on:
         - myproject-ape
      networks:
         - external_net

networks:
   external_net: {}

volumes:
   myproject-ape-vol1:
   myproject-bear-vol1:
   myproject-cat-vol1:
```
